## Plugins
eval %sh{
    kak-lsp --kakoune -s $kak_session && echo "
    	lsp-enable
    	lsp-diagnostic-lines-disable global
    "
}

## General options
set global scrolloff 3,3
set global startup_info_version -1
set global ui_options ncurses_assistant=off

## Visuals
colorscheme base16_termcolors
add-highlighter global/ show-matching
add-highlighter global/ line '%val{cursor_line}' CursorLine
add-highlighter global/ dynregex '%reg{/}' 0:SearchMatches
hook global BufCreate .* %{
    # Enable these on BufCreate so we can:
    # - disable them per buffer later on
    # - precisely define in which order they should be displayed
    add-highlighter buffer/number-lines number-lines -hlcursor -separator ' '
    try %{ lsp-diagnostic-lines-enable buffer }
    add-highlighter buffer/git-diff flag-lines GitDiffFlags git_diff_flags
    git update-diff
}
hook global BufWritePost .* %{ git update-diff }

# Force git gutter to always show by inserting a flag on line 0
declare-option -hidden line-specs git_diff_flags
hook global BufSetOption "git_diff_flags=(\d+) ('[^0].*)" %{
    # Note that -no-hooks doesn't seem to work in this case, so the regex above has been adjusted to
    # not match when our flag is present
    # Additionally, it doesn't seem like there's a way to expand %val{...} into multiple args without %sh
    eval -no-hooks %sh{
        echo set-option buffer git_diff_flags $kak_hook_param_capture_1 '0|H' $kak_hook_param_capture_2
    }
}
# Same as above, but for when there's no flags
hook global BufSetOption "git_diff_flags=(\d+)\s?" %{
    eval -no-hooks %sh{
        echo set-option buffer git_diff_flags $kak_hook_param_capture_1 '0|H'
    }
}

## Misc bindings
map global normal <C-w> %{ : new<ret> }
map global normal <C-y> %{ $ xsel -ib<ret> }
map global normal <C-p> %{ ! xsel -ob<ret> }

## Pager use
def -hidden pager-mode %{
    map buffer normal q %{: quit<ret>}
    remove-highlighter buffer/number-lines
}
hook global BufSetOption filetype=man %{ pager-mode }
