## Plugins
eval %sh{
    kak-lsp --kakoune -s $kak_session && echo "
        lsp-enable
        lsp-diagnostic-lines-disable global
    "
}

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/smarttab.kak" %{
    set-option global tabstop 4
    set-option global softtabstop 4
}

source "%val{config}/subl.kak"

## General options
set global scrolloff 3,3
set global startup_info_version -1
set global ui_options ncurses_assistant=off

## Visuals
colorscheme base16_termcolors
add-highlighter global/ show-matching
add-highlighter global/ line '%val{cursor_line}' CursorLine
add-highlighter global/ dynregex '%reg{/}' 0:SearchMatches
hook global WinCreate .* %{
    # Enable these on WinCreate so we can:
    # - disable them per window later on
    # - precisely define in which order they should be displayed
    add-highlighter window/number-lines number-lines -hlcursor -separator ' '
    try %{ lsp-diagnostic-lines-enable window }
    git show-diff
    expandtab
}
hook global BufWritePost .* %{ git update-diff }

# Force git gutter to always show by inserting a flag on line 0
declare-option -hidden line-specs git_diff_flags
hook global BufSetOption "git_diff_flags=(\d+) ('[^0].*)" %{
    # Note that -no-hooks doesn't seem to work in this case, so the regex above has been adjusted to
    # not match when our flag is present
    # Additionally, it doesn't seem like there's a way to expand %val{...} into multiple args without %sh
    eval -no-hooks %sh{
        echo set-option buffer git_diff_flags $kak_hook_param_capture_1 '0|H' $kak_hook_param_capture_2
    }
}
# Same as above, but for when there's no flags
hook global BufSetOption 'git_diff_flags=(\d+)\s?' %{
    eval -no-hooks %sh{
        echo set-option buffer git_diff_flags $kak_hook_param_capture_1 '0|H'
    }
}

## Misc commands
define-command try-comment %{
    try %{
        comment-block
    } catch %{
        comment-line
    }
}

## Misc bindings
map global normal <C-w> ': new<ret>'
map global normal <C-y> '<A-|> xsel -ib<ret>'
map global normal <C-p> '! xsel -ob<ret>'
map global normal <C-v> ': set-register /<ret><C-l>'
# ctrl+/ (https://github.com/mawww/kakoune/issues/2553)
map global normal <> ': try-comment<ret>'
map global normal <C-d> 'xyp'

## Pager use
def -hidden pager-mode %{
    map window normal q %{: quit<ret>}
    remove-highlighter window/number-lines
}
hook global WinSetOption filetype=man %{ pager-mode }

hook -group git-highlight global WinSetOption filetype=git %{
    add-highlighter window/git group
    add-highlighter window/git/ regex '^(commit) ([0-9a-f]+)(.*?)$' 1:yellow 2:red
    add-highlighter window/git/ regex '^([a-zA-Z_-]+:) (.*?)$' 1:green 2:magenta
    add-highlighter window/git/ ref diff
}
hook -group git-highlight global WinSetOption filetype=(?!git).* %{ remove-highlighter window/git }
