#!/bin/sh

SOCKET_PATH=$XDG_RUNTIME_DIR/playerctlctl

function join_by {
  local IFS="$1"
  shift
  echo "$*"
}

method=$1
shift
args=$(join_by , $@)

printf '{"jsonrpc": "2.0", "method": "%s", "params": [%s], "id": 1}\n' "$method" "$args" | socat - UNIX-CONNECT:$SOCKET_PATH
